### ISSUE TITLE
i think this repo need some todo list or milestone ?

### ISSUE THREAD

**Issue by jhonoryza** [devaslanphp/forumium#6]
i check some feature in forum is not implemented? maybe you should tell in documentation or readme what is working or not working so everyone can checked or help

**Comment by heloufir** [comment]
Yes, you are right I will create an empty project on this repo so everyone can add ideas.

You can check the project section of the repo.

**Comment by heloufir** [comment]
You can add your ideas as issues or tasks inti the project into the BACKLOG column
