### ISSUE TITLE
Use users for an existent Laravel app on Fórum

### ISSUE THREAD

**Issue by Geovanek** [devaslanphp/forumium#8]
Is it possible to use a database and existing users of a laravel application to use these same users in the forum?

**Comment by heloufir** [comment]
Yes of course, you only need to have the same migration name for the users ...etc (the forum uses the laravel migrations for users), or you can delete/change the migration of the forum after clone it before executing the migrations in your database.

> Or better, what I suggest is you clone the project, migrate your database, and then export your data and import them into the forumium database.
